package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/r351574nc3/turbo-octo-eureka/models"
)

/*FindPetByIDOK pet response

swagger:response findPetByIdOK
*/
type FindPetByIDOK struct {

	// In: body
	Payload *models.Pet `json:"body,omitempty"`
}

// NewFindPetByIDOK creates FindPetByIDOK with default headers values
func NewFindPetByIDOK() *FindPetByIDOK {
	return &FindPetByIDOK{}
}

// WithPayload adds the payload to the find pet by Id o k response
func (o *FindPetByIDOK) WithPayload(payload *models.Pet) *FindPetByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find pet by Id o k response
func (o *FindPetByIDOK) SetPayload(payload *models.Pet) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindPetByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*FindPetByIDDefault unexpected error

swagger:response findPetByIdDefault
*/
type FindPetByIDDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewFindPetByIDDefault creates FindPetByIDDefault with default headers values
func NewFindPetByIDDefault(code int) *FindPetByIDDefault {
	if code <= 0 {
		code = 500
	}

	return &FindPetByIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the find pet by id default response
func (o *FindPetByIDDefault) WithStatusCode(code int) *FindPetByIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the find pet by id default response
func (o *FindPetByIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the find pet by id default response
func (o *FindPetByIDDefault) WithPayload(payload *models.Error) *FindPetByIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find pet by id default response
func (o *FindPetByIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindPetByIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
